language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
addons:
  postgresql: 9.3
before_script:
  - psql -c 'create database sewc_test' -U postgres
  - cp ./config/database.yml.example ./config/database.yml
  - "RACK_ENV=test bundle exec rake db:migrate"
